config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :lists , only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :list
  belongs_to :movie
  validates :comment, length: { minimum: 6 }
  validates :list, :uniqueness => {:scope => :movie_id}
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, :through => :bookmarks
  has_one_attached :photo
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, :through => :bookmarks
  validates :title, presence: true
  validates :overview, presence: true
  validates :title, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end
  def create
    @bookmark = Bookmark.new(bookmark_params)
    if @bookmark.save
        redirect_to list_path(List.find(params[:list_id]))
    else
      render :new
    end
  end
  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(List.find(params[:list_id]))

  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :list_id, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @list = List.all
    @new_list = List.new
  end
  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end
  def new
    @list = List.new
  end
  def create
    @list = List.new(list_params)
    @list.save
    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/views/bookmarks/new.html.erb
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :list %>
  <%= f.association :movie %>
  <%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class='banner'style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= asset_path('Jiangnan_Photography.jpeg')%>)">
<p>Save you favorites movies <br>and watch them later</p></div>
<div class= 'lists'>
  <h1>My Lists</h1>
  <ul>
    <% @list.each do |list| %>

      <%if list.photo.attached?  %>
        <div class='list' style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path(list.photo.key), height: 300, crop: :fill %>')">
          <li ><%= link_to list.name,list_path(list) %></li>

      </div>
    <%else  %>
    <div class='list'>
          <li><%= link_to list.name,list_path(list) %></li>
      </div>

    <%end %>
    <%end  %>
  </ul>

</div>



<br><br>
<%= simple_form_for (@new_list) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>

app/views/lists/new.html.erb
<br><br>
<%= simple_form_for (@list) do |f| %>
  <%= f.input :name %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>

app/views/lists/show.html.erb
<br><br><%= @list.name %> <br>
<%= cl_image_tag @list.photo.key, height: 300, crop: :fill %>
<ul>
<% @list.bookmarks.each do |bookmark| %>
  <li><%= bookmark.comment %>
  <p>Movie: <%= Movie.find(bookmark.movie_id).title %></p>
  <%= link_to 'Delete',list_bookmark_path(bookmark),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %>
  </li>
<%end  %>
</ul>
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :list %>
  <%= f.association :movie %>
  <%= f.button :submit %>
<% end %>